[package]
name = "last_click_wins"
version = "0.1.0"
authors = []

[addresses]
last_click_wins = "_"

[dev-addresses]
last_click_wins = "0x2"

[dependencies]
# mainnet requires latest Aptos CLI (e.g. 1.8+). For older CLI use: rev = "aptos-node-v1.8.0"
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
